1. Импортируем библиотеку Pandas для работы с датасетами. Выведем первые пять строк датасета и продемонстрируем структуру:

In [2]:
import pandas as pd

df = pd.read_csv("/content/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

2. Выведем информацию о датасете: типы данных по столбцам, количество пропусков и описательную статистику:

In [3]:
print("Информация о типах данных и ненулевых значениях:")
df.info()

print("\nКоличество пропусков по столбцам:")
print(df.isna().sum())

print("\nОписательная статистика (округленная до 2 знаков):")
print(df.describe().round(2))

Информация о типах данных и ненулевых значениях:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Количество пропусков по столбцам:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Описательная статистика (округленная до 2 знаков):
       PassengerId  Survived  Pclass     Age   SibSp   Parch    Fare
count       891.00    891.00  891.00  714.00  891.00  891.00  891.00
mean        446.00      0.38    2.31   29.70    0.52    0.38   32.20
std         257.35      0.49    0.84   14.53    1.10    0.81   49.69
min           1.00      0.00    1.00    0.42    0.00    0.00    0.00
25%         223.50      0.00    2.00   20.12    0.00    0.00    7.91
50%         446.00      0.00    3.00   28.00    0.00    0.00   14.45
75%         668.50      1.00    3.00   38.00    1.00    0.00   31.00
max         891.00      1.00    3.00   80.00    8.00    6.00  512.33

Рассчитаем процент выживаемости для каждого класса пассажиров: применим
группировку по признаку ```Pclass``` (классу) и произведем расчет процента по ```Survived```:

In [4]:
survival_by_class = df.groupby('Pclass')['Survived'].mean() * 100
survival_by_class.round(2)

Pclass
1    62.96
2    47.28
3    24.24
Name: Survived, dtype: float64

Найдем наиболее частотные имена среди женщин и мужчин в датафрейме.

Новым столбцом в датафрейме добавим ```firstname```, для каждой строки вызовем функцию ```real_first_name```

Поскольку женские имена иногда указываются в скобках рядом с мужским, для женщин необходима проверка на наличие скобок в имени. Для мужчин и женщин без скобок в имени используем первое слово после точки.

Далее группируем по полу и имени и выводим id (имя) первого вхождения максимального значения (```value_counts``` по имени)

In [5]:
def real_first_name(name):
    if '(' in name:
        inner = name.split('(')[1].split(')')[0]
        return inner.split()[0].replace('"', '')

    if '.' in name:
        parts = name.split('.')
        first_name = parts[1].strip().split(' ')[0]
        return first_name.replace('"', '')

    return name

df['firstname'] = df['Name'].apply(real_first_name)

print('Самое популярное мужское имя:', df[df['Sex'] == 'male']['firstname'].value_counts().idxmax()
)
print('Самое популярное женское имя:', df[df['Sex'] == 'female']['firstname'].value_counts().idxmax()
)

Самое популярное мужское имя: William
Самое популярное женское имя: Mary

Группируем данные по полу, классу и имени. С помощью функции ```mode``` найдем самые частотные имена по классам - для женщин и мужчин отдельно:

In [6]:
df.groupby(['Pclass', 'Sex'])['firstname'].agg(lambda x: x.mode())

Pclass  Sex
1       female    [Elizabeth, Margaret]
        male                    William
2       female                Elizabeth
        male                    William
3       female                     Anna
        male                    William
Name: firstname, dtype: object

Выведем данные обо всех пассажирах старше 44 лет:

In [7]:
df[(df['Age'] > 44)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,firstname
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Elizabeth
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,Mary
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,Edward
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,Myna
...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S,Peter
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,Margaret
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Sallie
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,Victor
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Lily

Выведем данные о мужчинах старше 44 лет:

In [8]:
df[(df['Age'] < 44)&(df['Sex'] == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S,Owen
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S,William
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S,Gosta
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S,William
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S,Anders
...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.500,NaN,S,Frederick
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S,Henry
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S,Juozas
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C,Karl
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q,Patrick

Для определения количества мест в каютах удалим пропуски, разобьем текст по пробелам и посчитаем количество кают, указанных для каждого пассажира.
После этого вычислим кол-во кают с разным числом мест:

In [ ]:
df['Cabin'].dropna().str.split().str.len().value_counts().sort_index()

Cabin
1    180
2     16
3      6
4      2
Name: count, dtype: int64

Выберем строки датафрейма с пассажирами, у которых нет братьев/сестер и родитетелей/детей на борту и получим размер выборки:

In [ ]:
len(df[(df['SibSp'] ==0) & (df['Parch'] == 0)])

537